// <auto-generated />
namespace General.Data.Sql.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.2-21211")]
    public sealed partial class ss : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ss));
        
        string IMigrationMetadata.Id
        {
            get { return "201402280920549_ss"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
